- `[부스트캠프 AI Tech 프리코스] 인공지능 기초 다지기 (2)`를 듣고 실습코드 작성한 주피터 노트북임
    - 이 강의를 듣는 목적 
        - 1년 동안 AI 책도 많이 읽고 강좌도 많이 들었으니, 내가 정확하게 얼마나 알고 있는지 테스트하는 용도
    - 이 강의를 그러면 언제까지 끝낼거냐
        - 7월 3주차까지 + 빅분개 복습과 같이 진행 (그 이후엔 파이토치 교과서 정독으로 넘어갈거임. 이번 방학의 목표는 기본 다지기 + 자격증 많이)
- `[부스트캠프 AI Tech 프리코스] 인공지능 기초 다지기 (2)`에서 배우는 것 
    - 선형대수학 기초 : 벡터, 행렬, 미분
    - 딥러닝 논문 읽기에 도움이 될 수학 기초
        - 딥러닝 학습 방법 (back propagation)
        - 확률론
        - 통계학
        - 베이즈 통계학
    - CNN 원리
    - RNN 원리 
    - Pytorch 기초
    - Pytorch 구조 및 활용법
    - CNN, RNN, Transformer, GAN using Pytorch 
    

-----

### seminar - BASIC-AI-2 : vector and matrix, gradient descent

In [31]:
import numpy as np

In [32]:
x = np.array([1, 2, 3]) 
y = np.array([2, -3 ,4]) # 행벡터 선언

print (x + y) # element끼리의 덧셈
print (x - y) # element끼리의 뺄셈
print (x * y) # element끼리의 곱셈
print (2 * x) # 실수배

[ 3 -1  7]
[-1  5 -1]
[ 2 -6 12]
[2 4 6]


In [33]:
# l1 norm : 절댓값을 이용한 원점과의 거리
# l2 norm : 제곱값을 이용한 원점과의 거리
# regularizaton할 때 사용

def l1_norm(x) :
    print (x)
    x_norm = np.abs(x)
    print ("abs : ", x_norm)
    x_norm = np.sum(x) 
    print ("sum : ", x_norm)
    return x_norm

def l2_norm(x) : 
    print (x)
    x_norm = x * x
    print ("square : ", x_norm)
    x_norm = np.sum(x_norm) 
    print ("sum : ", x_norm)
    x_norm = np.sqrt(x_norm)
    print ("sqrt : ", x_norm)
    return x_norm

print (l1_norm(y))
print (l2_norm(y))
print (np.linalg.norm(y)) # l2_norm 함수랑 똑같은 역할 함

[ 2 -3  4]
abs :  [2 3 4]
sum :  3
3
[ 2 -3  4]
square :  [ 4  9 16]
sum :  29
sqrt :  5.385164807134504
5.385164807134504
5.385164807134504


In [34]:
x = np.array([[1, 2, 3], 
              [4, 1, 6],
              [7, 8, 1]])
y = np.array([[1, 1, 1], 
             [-1, -1, -1], 
             [-1, 1, 0]])
print (x) # 행렬 : 행벡터의 집합
x.shape

[[1 2 3]
 [4 1 6]
 [7 8 1]]


(3, 3)

In [35]:
print (x + y)
print (x - y)
print (x * y) # element-wise multiplication
print (2 * x)

[[2 3 4]
 [3 0 5]
 [6 9 1]]
[[0 1 2]
 [5 2 7]
 [8 7 1]]
[[ 1  2  3]
 [-4 -1 -6]
 [-7  8  0]]
[[ 2  4  6]
 [ 8  2 12]
 [14 16  2]]


In [36]:
x @ y # 행렬의 곱셈 수행

array([[-4,  2, -1],
       [-3,  9,  3],
       [-2,  0, -1]])

In [37]:
def mat_mul(x, y):
    if x.shape[1] != y.shape[0]:
        print("not equal shape for matrix multiplication")
        return None
    
    rst = np.zeros((x.shape[0], y.shape[1]))
    
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            sum = 0
            for k in range(x.shape[1]):  
                sum += x[i][k] * y[k][j]
            rst[i][j] = sum
            
    return rst

print(mat_mul(x, y))


[[-4.  2. -1.]
 [-3.  9.  3.]
 [-2.  0. -1.]]


In [38]:
np.inner(x, y) # 행렬의 내적

array([[  6,  -6,   1],
       [ 11, -11,  -3],
       [ 16, -16,   1]])

In [39]:
x_inversed = np.linalg.inv(x)
print (x_inversed)
print (x @ x_inversed) # <-- 단위행렬 I로 됨 (컴퓨터는 정확한 수치가 아니니 0과 가까운 숫자로)

[[-0.45192308  0.21153846  0.08653846]
 [ 0.36538462 -0.19230769  0.05769231]
 [ 0.24038462  0.05769231 -0.06730769]]
[[ 1.00000000e+00 -1.38777878e-17  1.38777878e-17]
 [-1.11022302e-16  1.00000000e+00 -2.77555756e-17]
 [ 3.88578059e-16 -1.38777878e-17  1.00000000e+00]]


In [40]:
# 다항함수의 미분

import sympy as sym
from sympy.abc import x # x 변수 가져오기

poly = x**2+2*x+1
print (sym.diff(poly, x))

2*x + 2


In [43]:
def poly_deri(poly):
    operand = []
    sign = []

    st = ''
    for i in range(len(poly)):
        if poly[i] in ['+', '-']:
            if st != '':
                operand.append(st)
                st = ''
            sign.append(poly[i])
        else:
            st += poly[i]
    if st != '':
        operand.append(st)

    if len(sign) < len(operand):
        sign = ['+'] + sign

    new_operands = []

    for i in range(len(operand)):
        term = operand[i]

        if 'x**' in term:
            coef_part, power_part = term.split('x**')
            if coef_part in ['', '+']:
                coef = 1
            elif coef_part == '-':
                coef = -1
            else:
                coef = int(coef_part.replace('*', ''))

            power = int(power_part)
            new_coef = coef * power
            new_power = power - 1

            if new_power == 1:
                new_term = f'{new_coef}*x'
            elif new_power == 0:
                new_term = f'{new_coef}'
            else:
                new_term = f'{new_coef}*x**{new_power}'

            new_operands.append(new_term)

        elif 'x' in term:
            coef_part = term.replace('x', '').replace('*', '')
            if coef_part in ['', '+']:
                coef = 1
            elif coef_part == '-':
                coef = -1
            else:
                coef = int(coef_part)
            new_term = f'{coef}'
            new_operands.append(new_term)

        else:
            new_operands.append('0')

    result = ''
    for s, t in zip(sign, new_operands):
        if t == '0':
            continue
        if result == '' and s == '+':
            result += t
        else:
            result += s + t

    return result

poly = 'x**2+2*x+1'
print(poly_deri(poly))

2*x+2


In [ ]:
# 경사하강법 구현 (global minima 찾기 when function's shape must be convex)

if