In [25]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init

W = torch.zeros([4, 1], requires_grad = True) 
b = torch.zeros(1, requires_grad = True)

data = {
    'name': ['Kim', 'Lee', 'Park', 'Choi', 'Jung', 'Go', 'Woo', 'Min', 'Kang'],
    'GPA': [3.8, 3.2, 3.7, 4.2, 2.6, 3.4, 4.1, 3.3, 3.9],
    'TOEIC': [700, 650, 820, 830, 550, 910, 990, 870, 650],
    'Award': [80, 90, 70, 50, 90, 30, 70, 60, 80],
    'Etc': [50, 30, 40, 70, 60, 40, 20, 60, 50]
}

gpa_tensor = torch.FloatTensor(data['GPA'])
toeic_tensor = torch.FloatTensor(data['TOEIC'])
award_tensor = torch.FloatTensor(data['Award'])
etc_tensor = torch.FloatTensor(data['Etc'])

print("GPA Tensor:")
print(gpa_tensor)

print("\nTOEIC Tensor:")
print(toeic_tensor)

print("\nAward Tensor:")
print(award_tensor)

print("\nEtc Tensor:")
print(etc_tensor)

X_train = torch.FloatTensor([
    data['GPA'],
    data['TOEIC'],
    data['Award'],
    data['Etc']
])

y_train = torch.FloatTensor([85, 80, 78, 87, 85, 70, 81, 88, 84]) 

print(X_train.shape, y_train.shape)


GPA Tensor:
tensor([3.8000, 3.2000, 3.7000, 4.2000, 2.6000, 3.4000, 4.1000, 3.3000, 3.9000])

TOEIC Tensor:
tensor([700., 650., 820., 830., 550., 910., 990., 870., 650.])

Award Tensor:
tensor([80., 90., 70., 50., 90., 30., 70., 60., 80.])

Etc Tensor:
tensor([50., 30., 40., 70., 60., 40., 20., 60., 50.])
torch.Size([4, 9]) torch.Size([9])


In [32]:
X_train_t = torch.transpose(X_train, 0, 1)
print (X_train_t.shape)
print (X_train_t)

torch.Size([9, 4])
tensor([[  3.8000, 700.0000,  80.0000,  50.0000],
        [  3.2000, 650.0000,  90.0000,  30.0000],
        [  3.7000, 820.0000,  70.0000,  40.0000],
        [  4.2000, 830.0000,  50.0000,  70.0000],
        [  2.6000, 550.0000,  90.0000,  60.0000],
        [  3.4000, 910.0000,  30.0000,  40.0000],
        [  4.1000, 990.0000,  70.0000,  20.0000],
        [  3.3000, 870.0000,  60.0000,  60.0000],
        [  3.9000, 650.0000,  80.0000,  50.0000]])


In [54]:
lrs = [0.0001, 0.00001, 0.000001, 0.0000001]
num_epochs = [10, 100, 500, 1000, 2500, 5000, 10000]
dir_rsts = {}

for lr in lrs:
    W = torch.zeros([4,1], requires_grad = True) 
    b = torch.zeros(1, requires_grad = True)
    
    optimizer = optim.SGD([W, b], lr=lr)
    dir_rsts[str(lr)] = {}
    
    for ep in num_epochs:
        print(f'< Before Train : {lr} {ep}>')
        print('W = ', W)
        print('b =', b)
        costs = []
        
        for epoch in range(ep):
            hypothesis = torch.matmul(X_train_t, W) + b
            cost = torch.mean((hypothesis - y_train) ** 2)
            
            optimizer.zero_grad()
            cost.backward()
            optimizer.step()
            
            if epoch % 100 == 0:
                print('Epoch: %d , Cost: %f' %(epoch, cost))
            
            costs.append(float(cost))
            
        print(f'< After Train : {lr} {ep}>')
        print('W = ', W)
        print('b =', b)
        print("\n --------------------------- \n")
        
        dir_compo = {
            'W': W.detach().clone(), 
            'b': b.detach().clone(),
            'costs': costs
        }
        dir_rsts[str(lr)][str(ep)] = dir_compo

< Before Train : 0.0001 10>
W =  tensor([[0.],
        [0.],
        [0.],
        [0.]], requires_grad=True)
b = tensor([0.], requires_grad=True)
Epoch: 0 , Cost: 6751.555664
< After Train : 0.0001 10>
W =  tensor([[-3.9418e+17],
        [-8.6826e+19],
        [-7.2472e+18],
        [-4.9883e+18]], requires_grad=True)
b = tensor([-1.0884e+17], requires_grad=True)

 --------------------------- 

< Before Train : 0.0001 100>
W =  tensor([[-3.9418e+17],
        [-8.6826e+19],
        [-7.2472e+18],
        [-4.9883e+18]], requires_grad=True)
b = tensor([-1.0884e+17], requires_grad=True)
Epoch: 0 , Cost: inf
< After Train : 0.0001 100>
W =  tensor([[nan],
        [nan],
        [nan],
        [nan]], requires_grad=True)
b = tensor([nan], requires_grad=True)

 --------------------------- 

< Before Train : 0.0001 500>
W =  tensor([[nan],
        [nan],
        [nan],
        [nan]], requires_grad=True)
b = tensor([nan], requires_grad=True)
Epoch: 0 , Cost: nan
Epoch: 100 , Cost: nan
Epoch:

Epoch: 100 , Cost: nan
Epoch: 200 , Cost: nan
Epoch: 300 , Cost: nan
Epoch: 400 , Cost: nan
Epoch: 500 , Cost: nan
Epoch: 600 , Cost: nan
Epoch: 700 , Cost: nan
Epoch: 800 , Cost: nan
Epoch: 900 , Cost: nan
< After Train : 1e-05 1000>
W =  tensor([[nan],
        [nan],
        [nan],
        [nan]], requires_grad=True)
b = tensor([nan], requires_grad=True)

 --------------------------- 

< Before Train : 1e-05 2500>
W =  tensor([[nan],
        [nan],
        [nan],
        [nan]], requires_grad=True)
b = tensor([nan], requires_grad=True)
Epoch: 0 , Cost: nan
Epoch: 100 , Cost: nan
Epoch: 200 , Cost: nan
Epoch: 300 , Cost: nan
Epoch: 400 , Cost: nan
Epoch: 500 , Cost: nan
Epoch: 600 , Cost: nan
Epoch: 700 , Cost: nan
Epoch: 800 , Cost: nan
Epoch: 900 , Cost: nan
Epoch: 1000 , Cost: nan
Epoch: 1100 , Cost: nan
Epoch: 1200 , Cost: nan
Epoch: 1300 , Cost: nan
Epoch: 1400 , Cost: nan
Epoch: 1500 , Cost: nan
Epoch: 1600 , Cost: nan
Epoch: 1700 , Cost: nan
Epoch: 1800 , Cost: nan
Epoch: 1900 

Epoch: 1900 , Cost: 45.625507
Epoch: 2000 , Cost: 45.618008
Epoch: 2100 , Cost: 45.611313
Epoch: 2200 , Cost: 45.605343
Epoch: 2300 , Cost: 45.599991
Epoch: 2400 , Cost: 45.595230
< After Train : 1e-06 2500>
W =  tensor([[0.0068],
        [0.0562],
        [0.3760],
        [0.2641]], requires_grad=True)
b = tensor([0.0044], requires_grad=True)

 --------------------------- 

< Before Train : 1e-06 5000>
W =  tensor([[0.0068],
        [0.0562],
        [0.3760],
        [0.2641]], requires_grad=True)
b = tensor([0.0044], requires_grad=True)
Epoch: 0 , Cost: 45.590950
Epoch: 100 , Cost: 45.587112
Epoch: 200 , Cost: 45.583656
Epoch: 300 , Cost: 45.580582
Epoch: 400 , Cost: 45.577812
Epoch: 500 , Cost: 45.575340
Epoch: 600 , Cost: 45.573116
Epoch: 700 , Cost: 45.571095
Epoch: 800 , Cost: 45.569298
Epoch: 900 , Cost: 45.567688
Epoch: 1000 , Cost: 45.566227
Epoch: 1100 , Cost: 45.564919
Epoch: 1200 , Cost: 45.563751
Epoch: 1300 , Cost: 45.562702
Epoch: 1400 , Cost: 45.561756
Epoch: 1500 , C

Epoch: 1600 , Cost: 103.171997
Epoch: 1700 , Cost: 101.232841
Epoch: 1800 , Cost: 99.360268
Epoch: 1900 , Cost: 97.551758
Epoch: 2000 , Cost: 95.805313
Epoch: 2100 , Cost: 94.118652
Epoch: 2200 , Cost: 92.489784
Epoch: 2300 , Cost: 90.916672
Epoch: 2400 , Cost: 89.397430
< After Train : 1e-07 2500>
W =  tensor([[0.0034],
        [0.0789],
        [0.2087],
        [0.1130]], requires_grad=True)
b = tensor([0.0016], requires_grad=True)

 --------------------------- 

< Before Train : 1e-07 5000>
W =  tensor([[0.0034],
        [0.0789],
        [0.2087],
        [0.1130]], requires_grad=True)
b = tensor([0.0016], requires_grad=True)
Epoch: 0 , Cost: 87.930183
Epoch: 100 , Cost: 86.513176
Epoch: 200 , Cost: 85.144684
Epoch: 300 , Cost: 83.822952
Epoch: 400 , Cost: 82.546387
Epoch: 500 , Cost: 81.313492
Epoch: 600 , Cost: 80.122742
Epoch: 700 , Cost: 78.972679
Epoch: 800 , Cost: 77.861862
Epoch: 900 , Cost: 76.788994
Epoch: 1000 , Cost: 75.752716
Epoch: 1100 , Cost: 74.751862
Epoch: 1200 ,

In [52]:
print (dir_rsts.keys())

for key in dir_rsts : 
    print (key)
    print ("W : ", dir_rsts[key]['W'])
    print ("b : ", dir_rsts[key]['b'])

print (W) 
print (b)

test_data = torch.FloatTensor([[3.3, 700, 77, 84]])
predict = test_data.matmul(W) + b
pred_val = predict.squeeze().detach().numpy()
print (pred_val)

dict_keys(['0.0001', '1e-05', '1e-06', '1e-07'])
0.0001


TypeError: list indices must be integers or slices, not str